### PR TITLE
Make ready to include in library

### PR DESCRIPTION
**Pull request by ThomasWollmann**

### CODE REVIEW

**Comment by scopatz** [comment]
this didn't succeed

**Comment by ThomasWollmann** [comment]
@scopatz and why?

**Comment by scopatz** [comment]
Seems like it is a codec failure. Maybe you could try rerendering?

**Comment by ThomasWollmann** [comment]
Don't get why "CMAKE_POSITION_INDEPENDENT_CODE" should have this effect.

**Comment by scopatz** [comment]
Shouldn't it be `TRUE` or `ON` instead of `true`

**Comment by ThomasWollmann** [comment]
@scopatz Thanks!

**Comment by ThomasWollmann** [comment]
@ocefpaf can you please merge my PR?

**Pull request merged**
