### PR TITLE
Set cmake install libdir

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @SylvainCorlay! Please bump the build number :)

**Comment by SylvainCorlay** [comment]
Done!

**Comment by scopatz** [comment]
Thanks!

**Comment by scopatz** [comment]
Looks like the merge commit for this failed: https://travis-ci.org/conda-forge/pugixml-feedstock?utm_source=email&utm_medium=notification

Can you try rerendering please? Thanks

**Comment by SylvainCorlay** [comment]
ok, will do!

**Comment by SylvainCorlay** [comment]
conda-smithy does not seem to work with the current version of conda.

```
Traceback (most recent call last):
  File "/home/sylvain/miniconda3/bin/conda-smithy", line 4, in <module>
    import conda_smithy.cli
  File "/home/sylvain/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 14, in <module>
    from . import ci_register
  File "/home/sylvain/miniconda3/lib/python3.6/site-packages/conda_smithy/ci_register.py", line 10, in <module>
    from . import github
  File "/home/sylvain/miniconda3/lib/python3.6/site-packages/conda_smithy/github.py", line 16, in <module>
    from . import configure_feedstock
  File "/home/sylvain/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 48, in <module>
    from conda_build_all.version_matrix import special_case_version_matrix, filter_cases
  File "/home/sylvain/miniconda3/lib/python3.6/site-packages/conda_build_all/version_matrix.py", line 19, in <module>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
  File "/home/sylvain/miniconda3/lib/python3.6/site-packages/conda_build_all/version_matrix.py", line 19, in <genexpr>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
AttributeError: module 'conda.resolve' has no attribute 'NoPackagesFound'
```

**Comment by SylvainCorlay** [comment]
Oh, the readding seems to have solved the issue.

**Pull request merged**
